apiVersion: v1
kind: ServiceAccount
metadata:
  name: karpenter
  namespace: karpenter
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::YOUR_ACCOUNT_ID:role/KarpenterControllerRole-tnt-eu-observability-dev-eks
automountServiceAccountToken: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: karpenter-global-settings
  namespace: karpenter
data:
  aws.clusterName: tnt-eu-observability-dev-eks
  aws.defaultInstanceProfile: KarpenterNodeInstanceProfile-tnt-eu-observability-dev-eks
  aws.interruptionQueue: tnt-eu-observability-dev-eks
