apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
  labels:
    app: karpenter
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    # This will point to your GitHub repo
    repoURL: 'git@github.com:YOUR_USERNAME/k8s-gitops.git'
    path: apps/karpenter/overlays/dev
    targetRevision: main
  
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  
  revisionHistoryLimit: 10
