apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
  labels:
    app: karpenter
spec:
  project: default
  source:
    repoURL: https://charts.karpenter.sh
    chart: karpenter
    targetRevision: 1.6.0
    helm:
      values: |
        replicas: 1
        settings:
          clusterName: tnt-eu-observability-dev-eks
          clusterEndpoint: https://0225118442067E2CF58DE7E54EF7A3AF.gr7.eu-central-1.eks.amazonaws.com
          interruptionQueue: tnt-eu-observability-dev-eks-karpenter
        serviceAccount:
          create: true
          name: karpenter
        logLevel: info
  destination:
    server: https://kubernetes.default.svc
    namespace: karpenter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true