apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  - karpenter-nodepool.yaml

helmCharts:
  - name: karpenter
    repo: oci://public.ecr.aws/karpenter
    version: 1.6.0
    namespace: kube-system
    releaseName: karpenter
    valuesInline:
      replicas: 1
      settings:
        clusterName: tnt-eu-observability-dev-eks
        clusterEndpoint: https://0225118442067E2CF58DE7E54EF7A3AF.gr7.eu-central-1.eks.amazonaws.com
        aws:
          defaultInstanceProfile: karp-tnt-eu-d-eks
      logLevel: debug
      webhook:
        enabled: false
      nodeSelector:
        karpenter.sh/controller: 'true'
