apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
  labels:
    app: karpenter
spec:
  project: default
  
  source:
    repoURL: 'oci://public.ecr.aws/karpenter'
    chart: karpenter
    targetRevision: 1.0.8
    helm:
      values: |
        replicas: 1
        settings:
          clusterName: tnt-eu-observability-dev-eks
          clusterEndpoint: https://0225118442067E2CF58DE7E54EF7A3AF.gr7.eu-central-1.eks.amazonaws.com
          interruptionQueue: tnt-eu-observability-dev-eks
        logLevel: debug
        webhook:
          enabled: false
        serviceAccount:
          create: true
          name: karpenter
          # For Pod Identity, we don't need role-arn annotation
          # The Pod Identity association handles this automatically
  
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: karpenter
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  
  revisionHistoryLimit: 5
#       - CreateNamespace=true
  
#   # Keep history of deployments
#   revisionHistoryLimit: 5

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter-root
  namespace: argocd
spec:
  destination:
    namespace: karpenter
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'git@github.com:tomernos/Observability.git'
    path: ./karpenter
    targetRevision: main
    helm:
      values: |
        serviceAccount: 
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::654654526828:role/KarpenterController-20250830131454293200000002
        settings:
          clusterName: tnt-eu-observability-dev-eks
          clusterEndpoint: https://0225118442067E2CF58DE7E54EF7A3AF.gr7.eu-central-1.eks.amazonaws.com
          interruptionQueue: tnt-eu-observability-dev-eks-karpenter

      
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true