apiVersion: v1
kind: ConfigMap
metadata:
  name: karpenter-values
  namespace: karpenter
data:
  values.yaml: |
    replicas: 2
    settings:
      clusterName: tnt-eu-observability-dev-eks
      clusterEndpoint: https://0225118442067E2CF58DE7E54EF7A3AF.gr7.eu-central-1.eks.amazonaws.com
      interruptionQueue: tnt-eu-observability-dev-eks-karpenter
    logLevel: info
    webhook:
      enabled: false
