apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  role: "karp-tnt-eu-d-eks"  # שם ה-Instance Profile/Role של ה-NODES (חייב להתקיים)
  amiSelectorTerms:
    - alias: bottlerocket@latest
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "tnt-eu-observability-dev-eks"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "tnt-eu-observability-dev-eks"