# ArgoCD Configuration - Optimized for Karpenter autoscaling
global:
  domain: argocd.tomernos.xyz

syncSecret:
  enabled: true

certificate:
  enabled: false

configs:
  params:
    "server.insecure": true

controller:
  replicas: 1

repoServer:
  replicas: 1

server:
  replicas: 1
  service:
    type: ClusterIP

applicationSet:
  enabled: true
  replicas: 1


redis:
  enabled: true

